# Generated by Django 4.2.6 on 2023-10-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("Publicationdate",)},
        ),
        migrations.RenameField(
            model_name="post",
            old_name="slug",
            new_name="author",
        ),
        migrations.AddField(
            model_name="post",
            name="Publicationdate",
            field=models.TextField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="chapter",
            field=models.CharField(default=50, max_length=200),
            preserve_default=False,
        ),
    ]
