# Generated by Django 4.2.6 on 2023-10-28 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0002_alter_post_options_rename_slug_post_author_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-pub_date",)},
        ),
    ]
