# Generated by Django 4.2.6 on 2023-11-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0004_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="body",
            field=models.TextField(default=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="Publicationdate",
            field=models.CharField(max_length=200),
        ),
    ]
