# Generated by Django 4.2.6 on 2023-11-04 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mysite", "0005_post_body_alter_post_publicationdate"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Post",
            new_name="Book",
        ),
    ]
