# Generated by Django 4.2.4 on 2023-11-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0006_rename_post_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Episode',
            field=models.CharField(default=50, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='chapter',
            field=models.TextField(),
        ),
    ]
